language: rust

rust:
  - stable
  - beta
  - nightly

jobs:
  include:
    - stage: coverage
      rust: stable
      install:
        - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      script:
        - cargo tarpaulin --out Xml
        - bash <(curl -s https://codecov.io/bash)

    - stage: lint
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all -- --deny clippy::all

    - stage: format
      rust: nightly
      install:
        - rustup component add rustfmt || cargo install --git https://github.com/rust-lang/rustfmt --force --bin rustfmt
      script:
        - cargo fmt --all -- --check

    - stage: deploy
      branches:
        only:
          - master
      if: tag IS present AND fork = false
      rust: stable
      script:
        - set -e
        - cargo login $CRATES_IO_TOKEN
        - cargo package
        - cargo publish
